# Generated by Django 3.1.1 on 2020-09-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('speaker', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=100)),
                ('room_capacity', models.PositiveIntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('Morning', 'Morning'), ('Midmorning', 'Midmorning'), ('Afternoon', 'Afternoon')], max_length=50)),
            ],
        ),
    ]
