# Generated by Django 3.1.1 on 2020-09-18 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addevents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addevent',
            old_name='title',
            new_name='topic',
        ),
    ]
