# Generated by Django 3.1.1 on 2020-09-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addevents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addevent',
            name='date',
        ),
    ]
