# Generated by Django 3.1.1 on 2020-09-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addevents', '0002_auto_20200918_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='addevent',
            name='room_capacity',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
