# Generated by Django 3.1.1 on 2020-09-25 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerevent',
            name='email',
        ),
        migrations.AddField(
            model_name='registerevent',
            name='time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Midmorning', 'Midmorning'), ('Afternoon', 'Afternoon')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
